### ISSUE TITLE
Plan/Choose next functionality addition

### ISSUE THREAD

**Issue by chusloj** [RSBoone/Iris#2]
In choosing the next functionality addition (at least to start), a brief list of the common analyses we'd like to automate should be discussed here.

**Comment by RSBoone** [comment]
I will look into D3.js. As for the use of an HMM to predict market conditions, I don't know offhand any research that has done that before and I do not know any economists that do RE research.

Initial functionality does not have to focus on RE-A, it was just the first thing that came to mind. I will look for open projects that do that.

By developing an automated framework to pull data and run analyses regardless of subject will help me learn how to be more effective at my job so whatever we tackle is fine by me. If you have any data analytics needs that would apply to your job we can focus on that. If I can learn while developing something of immediate use, that would be preferable.

I found a link off of the BLS site that will help in developing a data scraping function. https://www.bls.gov/help/hlpforma.htm#AP The blog post by Daniel Strong also has good information. http://danstrong.tech/blog/BLS-API/
A package we could use can be found here: https://github.com/OliverSherouse/bls (Linked from Dan's blog)

I think my next step is to combine the spaCy module with the above to enable a user to request a dataset from the BLS. Do you have a coding step in mind? I know that you've said you aren't well versed in the NLP domain.
